services:
  fast_api_backend:
    image: .
    depends_on:
      - postgres_database
    ports:
      - "8000:8000"
  postgres_database:
    image: postgres:latest
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - "8080:8080"
    volumes:
      - database

volumes:
  database:
